server:
  tomcat.uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
    min-response-size: 1024
  port: ${SERVER_PORT:8080}

juggle:
  #Juggle服务部署的地址
  server-addr: http://127.0.0.1:9127
  #Juggle后台申请的令牌
  access-token: eyJ1c2VySWQiOjEsInRpbWVzdGFtcCI6MTcxMjE2MzgyNzE2OH0=

spring:
  devtools:
    restart:
      enabled: false
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: uu-book
  resources:
    static-locations: classpath:/
  http:
    encoding:
      enabled: true
      charset: UTF-8
  datasource:
    # 必填，与数据库同名
    database: ${DATASOURCE_DATABASE:uu_book}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/uu_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    #hikari数据库连接池
    hikari:
      pool-name: uu_book-hikaricp
      # 最小空闲连接数量
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 50
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 600000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: 'SELECT 1'
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

uu:
  book:
    auth:
      user-name: ${UU_AUTH_USERNAME:admin}
      password: ${UU_AUTH_PASSWORD:admin}

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF